CREATE TABLE tableList (
  table_id SERIAL PRIMARY KEY,
  table_name VARCHAR(150) NOT NULL,
  table_label VARCHAR(150) NOT NULL,
  table_row_count INT NOT NULL,
  table_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  table_modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);